//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiducolmena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacion
    {
        public long id { get; set; }
        public bool autorizacion_1 { get; set; }
        public bool autorizacion_2 { get; set; }
        public bool autorizacion_3 { get; set; }
        public string persona_id { get; set; }
    
        public virtual Persona_fidu Persona_fidu { get; set; }
    }
}
