//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiducolmena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiometricValidationState
    {
        public System.Guid CorrelationId { get; set; }
        public string CurrentState { get; set; }
        public int Version { get; set; }
        public string RequestNumber { get; set; }
        public string IdentificationType { get; set; }
        public string IdentificationNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string FirstSurname { get; set; }
        public string SecondSurname { get; set; }
        public string Email { get; set; }
        public string CellPhoneNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string Unit { get; set; }
        public string Product { get; set; }
        public Nullable<System.DateTime> UserInformationReceived { get; set; }
        public Nullable<System.DateTime> UserInformationStored { get; set; }
        public Nullable<System.DateTime> EmailToValidationSended { get; set; }
        public Nullable<System.DateTime> IdentityValidationReceived { get; set; }
        public Nullable<System.DateTime> IdentityValidationSended { get; set; }
        public Nullable<System.DateTime> DocumentsToSignReceived { get; set; }
        public Nullable<System.DateTime> DocumentsToSignSended { get; set; }
        public Nullable<System.DateTime> DocumentsSignedReceived { get; set; }
        public Nullable<System.DateTime> DocumentsSignedStored { get; set; }
        public bool SignatureStampsGenerated { get; set; }
        public bool SignatureEvidenceGenerated { get; set; }
        public string SignatureIntegrationServiceData { get; set; }
        public string Error { get; set; }
        public Nullable<System.DateTime> DateExpiry { get; set; }
        public Nullable<System.DateTime> LinkAccess { get; set; }
    }
}
