//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiducolmena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informacion_proyecto
    {
        public long id { get; set; }
        public string producto { get; set; }
        public long numero_encargo { get; set; }
        public string ciudad { get; set; }
        public string inmueble { get; set; }
        public string unidad { get; set; }
        public string torre { get; set; }
        public long valor_inmueble { get; set; }
        public long cantidad_garage { get; set; }
        public long cantidad_depositos { get; set; }
        public long valor_cuota_inicial { get; set; }
        public string persona_id { get; set; }
        public long Num_Enc_Fijo { get; set; }
    
        public virtual Persona_fidu Persona_fidu { get; set; }
    }
}
