//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiducolmena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona_val
    {
        public int Id { get; set; }
        public string IDENTIFICATION_NUMBER { get; set; }
        public string ID_IDENTIFICATION_TYPE { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string FIRST_SURNAME { get; set; }
        public string SECOND_SURNAME { get; set; }
        public string MAIL_ADDRESS { get; set; }
        public string TELEPHONE_NUMBER { get; set; }
        public string CELLPHONE_NUMBER { get; set; }
        public string REQUEST_NUMBER { get; set; }
        public string PRODUCT { get; set; }
        public string UNIT { get; set; }
    }
}
