//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiducolmena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_informacion_persona
    {
        public string identificacion { get; set; }
        public string tipo_identificacion { get; set; }
        public Nullable<System.DateTime> fecha_expedicion { get; set; }
        public string primer_nombre { get; set; }
        public string segundo_nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public bool autorizacion_1 { get; set; }
        public bool autorizacion_2 { get; set; }
        public bool autorizacion_3 { get; set; }
        public string producto { get; set; }
        public long numero_encargo { get; set; }
        public string ciudad { get; set; }
        public string inmueble { get; set; }
        public string unidad { get; set; }
        public string torre { get; set; }
        public long valor_inmueble { get; set; }
        public long cantidad_garage { get; set; }
        public long cantidad_depositos { get; set; }
        public long valor_cuota_inicial { get; set; }
        public System.DateTime fecha_diligenciamiento { get; set; }
        public string nombre_proceso { get; set; }
    }
}
